### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by ReactiveTurtle** [AlexPshkov/TravelLine#1]
Несколько советов:
Для полей объекта лучше добавлять модификатор readonly (если ты уверен, что он неизменяем)
Иммутабельность гарантирует безопасность работы с этими объектами (но тоже есть свои минусы)
В твоём случае это ни на что не повлияет

Именование и расположение файлов: в целом нравится структура, но я вот не сразу понял что за global-search
Вроде твой метод getFromBackend предназначен для того, чтобы получить любую сущность, но ты пользуешься 1
(абстрактно выглядит). Я так понял ты нацелен на гибкость и меньшее написание кода, но лучше выстраивать жёсткую структуру, тогда ты точечно сможешь убрать или добавить функционал затратив мало времени, но при этом на эту жёсткую структуру будет потрачено больше времени, чем при твоём подходе

**Comment by ReactiveTurtle** [comment]
Не нашёл возможности создания, обновления и удаления сущностей через UI

**Comment by AlexPshkov** [comment]
> Не нашёл возможности создания, обновления и удаления сущностей через UI

Но у нас в ТЗ нет такого. Там только "отображение сущностей"

**Comment by ReactiveTurtle** [comment]
Мой косяк, добавил)
Время есть до пятницы

**Comment by AlexPshkov** [comment]
Ок. Добавлю
